# Generated by Django 5.1.6 on 2025-02-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField()),
                ('time_registered', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
